[workspace]
members = ["cli", "greeter", "http", "name"]
resolver = "2"

[workspace.dependencies]
wit-bindgen = "0.29.0"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
