[package]
name = "greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]


[package.metadata.component]
package = "example:greeter"

[package.metadata.component.dependencies]
